#!/bin/sh

usage()
{
    echo "$0 [--prefix install_directory]"
    exit 1
}

INSTALL_DIR="/usr/local"

# Parse parameters
while [ $# -ge 1 ]; do
    case $1 in
        --prefix)
            INSTALL_DIR=$2
            shift
            ;;
        *)
            usage
            ;;
    esac
    shift
done

echo "Are you sure you want to uninstall Cappuccino ? [y/n]"
read answer

if [[ $answer == 'y' || $answer == 'Y' ]]; then
    # Remove binaries symbolic links
    BINS=`ls objj/bin`
    for BIN in $BINS
    do
        rm -f $INSTALL_DIR/bin/$BIN
    done
    
    # Remove ${INSTALL_DIR}/share/objj
    OBJJ_DIR="${INSTALL_DIR}/share/objj"
    rm -fR $OBJJ_DIR
    
    # Uninstall gems
    gem=`gem list --no-versions | grep objective-j`
    gem uninstall $gem
else
    echo "Nothing was removed."
    exit
fi

echo "Cappuccino Tools Uninstalled"
